export type DeepSkyObject = {
  "name": string;
  "type": string;
  "ra": string;
  "dec": string;
  "const": string;
  "maj_ax": number;
  "min_ax": number;
  "pos_ang": number;
  "b_mag": number;
  "v_mag": number;
  "j_mag": number;
  "h_mag": number;
  "k_mag": number;
  "surf_br": number;
  "hubble": string;
  "pax": number;
  "pm_ra": number;
  "pm_dec": number;
  "rad_vel": number;
  "redshift": number;
  "cstar_u_mag": number;
  "cstar_b_mag": number;
  "cstar_v_mag": number;
  "m": number;
  "ngc": number | string;
  "ic": number | string;
  "cstar_name": string;
  "identifiers": string;
  "common_names": string;
  "ned_notes": string;
  "open_ngc_notes": string;
  "sources": string;
}