// export enum AstroObjectTypes {
//   'GC' = 'Globular Cluster',
//   'OC' = 'Open Cluster',
//   'PN' = 'Planetary Nebula',
//   'Neb' = 'Nebula',
//   'Gxy' = 'Galaxy',
//   'OC+Neb' = 'Open Cluster with Nebula',
//   'Ast' = 'Asterism',
// }
// export enum AstroObjectTypes {
//   'Open Cluster' = 'OCL',
//   'Globular Cluster' = 'GCL',
//   'Planetary Nebula' = 'PN',
//   'Nebula' = 'NEB',
//   'Culster with Nebula' = 'CL+N',
//   'Galaxy' = 'G',
//   'Dark Nebula' = "DRKN",
//   'HII Region' = 'HII',
//   'Star asterism' = '*ASS',
//   'Double star' = "**",
//   'Unknown' = 'OTHER',
//   'Reflection nebula' = 'RFN',
//   'Galaxy pair' = 'GPAIR',
//   'Triple galaxy' = 'GTRPL',
//   'Star' = '*',
//   'Supernova remnent' = 'SNR',
//   'Galaxy group' = 'GGROUP',
// }

export enum AstroObjectTypes {
    'GCL' = 'Globular Cluster',
    'OCL' = 'Open Cluster',
    'PN' = 'Planetary Nebula',
    'NEB' = 'Nebula',
    'CL+N' = 'Cluster with Nebula',
    'G' = 'Galaxy',
    'DRKN' = 'Dark Nebula',
    'HII' = 'HII Region',
    '*ASS' = 'Star asterism',
    '**' = 'Double star',
    'OTHER' = 'Unknown',
    'RFN' = 'Reflection nebula',
    'GPAIR' = 'Galaxy pair',
    'GTRPL' = 'Triple galaxy',
    '*' = 'Star',
    'SNR' = 'Supernova remnent',
    'GGROUP' = 'Galaxy group',
  }

